var config = {
    eventCustom: {
        MSG_GO: "msg_go",
        MSG_BUY: "msg_buy_land",
        MSG_PAY_TOLLS: "msg_pay_tolls",
        MSG_MOVE_ONE_STEP: "msg_move_one_step",
        MSG_DIMISS_DIALOG: "msg_dimiss_dialog",
        MSG_RANDOM_ASK_EVENT: "msg_random_ask_event",
        MSG_BLOCK_WAY_EVENT: "msg_block_way_event",
        MSG_PICKONE_TOGO: "msg_pickone_togo",
        MSG_AROUND_LAND: "msg_around_land",
        MSG_HANDLE_PROP_EVENT: "msg_handle_prop_event",
        MSG_ROUND_COUNT: "msg_round_count",
        MSG_GAME_OVER: "msg_game_over",
        MSG_REST: "msg_rest",
        MSG_STRENGTH_UP: "msg_strength_up",
        MSG_LOTTERY: "msg_lottery",
        MSG_STOCK: "msg_stock",
        MSG_DIMISS_DIALOG: "msg_dimiss_dialog",
        MSG_STOCK_LAYER_DISMISS: "msg_stock_layer_dismiss",
        MSG_USE_SKILL: "msg_use_skill",
        MSG_LOAD_GAME: "msg_load_game"
    },
    eventTag: {
        MSG_GO_HIDE_TAG: 0,
        MSG_GO_SHOW_TAG: 1,
        MSG_BUY_BLANK_TAG: 2,
        MSG_BUY_LAND_1_TAG: 3,
        MSG_BUY_LAND_2_TAG: 4,
        MSG_PICKONE_TOGO_TAG: 5,
        MSG_PAY_TOLLS_1_TAG: 6,
        MSG_PAY_TOLLS_2_TAG: 7,
        MSG_PAY_TOLLS_3_TAG: 8,
        MSG_AROUND_LAND_TAG: 9,
        MSG_RANDOM_ASK_EVENT_TAG: 10,
        MSG_BLOCK_WAY_EVENT_TAG: 11,
        MSG_HANDLE_PROP_EVENT_TAG: 12,
        MSG_ROUND_COUNT_TAG: 13,
        MSG_REST_TAG: 14,
        MSG_STRENGTH_UP30_TAG: 15,
        MSG_STRENGTH_UP50_TAG: 16,
        MSG_STRENGTH_UP80_TAG: 17,
        MSG_LOTTERY_TAG: 18,
        MSG_MOVE_ONE_STEP_TAG: 19,
        MSG_DIMISS_DIALOG_PUBLISH_LOTTERY_TAG: 20,
        MSG_STOCK_TAG: 21,
        MSG_STOCK_LAYER_DISMISS_TAG: 22,
        MSG_USE_SKILL_TAG: 23,
        MSG_GAME_OVER_TAG: 24,
        MSG_LOAD_GAME_TAG: 25
    },
    itemType: {
        ITEM_CRAB: 0,
        ITEM_BALL: 1,
        ITEM_STRENGTH_UP: 2,
        ITEM_FOG: 3,
        ITEM_EMERGENCY: 4,
        ITEM_STRETCHER: 5
    },
    popupLayer: {
      titleTag: 20000,
      contentTag: 20001
    },

    mapCount: 3,
    PLAYER_1_NAME: "player1",
    PLAYER_1_TAG: 1,
    PLAYER_2_NAME: "player2",
    PLAYER_2_TAG: 2,
    LAND_BLANK_MONEY: 1000,
    LAND_LEVEL_1_MONEY: 2000,
    LAND_LEVEL_2_MONEY: 3000,
    LOTTERY_ROUND_FREQUENTLY: 10,
    LOTTERY_WIN_MONEY: 50000
}